### ISSUE TITLE
Libs

### ISSUE THREAD

**Issue by eltech35** [NextDesignSolutions/NextJtag#1]
Under Ethos 1.3.3: (ubuntu 14... i know...)
./nextjtag: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./nextjtag)

idem on Ubuntu 16 desktop

Can you static link a version somewhere please ?

**Comment by mbrase** [comment]
There are some potential licensing issues with static linking glibc, so I can't provide a version that is completely statically linked at this time.

However, I have heard that some of the older versions of nextjtag work on ethos.  What version gave you the error above?  Can you try version 2.2.2 and see if that works?

**Comment by mbrase** [comment]
I have made some changes to my build system, and have uploaded v2.3.2.  I think this version should run on ethos, but don't have access to a system to try it out.  Please give it a try and let me know if you are still seeing the issue.

**Comment by eltech35** [comment]
Thanks, will do

Cordialement,

Christophe TOUZET
Elichain Technology
ctouzet@elichain.com
